/**
 * client/constants/projectTemplates.ts
 * Comprehensive example project templates for NexusFlow V4 workspace creation.
 * Every template contains domain-specific context of at least 1,200 characters (target: 1,500–2,000 chars).
 */
import { MethodologyType } from "@/utils/methodologyConfig";

export type ProjectTemplate = {
  id: string;
  title: string;
  domain: string;
  methodology: MethodologyType;
  domainIcon: string;
  tags: string[];
  objective: string;
  description: string;
  features: string[];
  requirements: string[];
  deliverables: string[];
  suggestedSkills: string[];
  clientRequirements: string;
};

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: "ai-irrigation",
    title: "AI Irrigation System",
    domain: "IoT",
    methodology: "WATERFALL",
    domainIcon: "water-outline",
    tags: ["IoT", "AI", "Agriculture", "ESP32"],
    objective: "Build an AI-driven smart irrigation system using IoT sensors for automated crop watering.",
    description: "The AI-Driven Smart Irrigation and Soil Health Monitoring Platform is an autonomous agricultural IoT ecosystem designed for modern commercial farms, greenhouses, and precision agriculture cooperatives. The system addresses water scarcity, unpredictable weather patterns, and excessive energy consumption by providing automated, sensor-guided irrigation management across multiple distributed farming zones. Field deployment consists of low-power ESP32 microcontrollers connected to capacitive soil moisture sensor arrays, soil temperature probes, and ambient DHT22 humidity sensors. Real-time sensor readings are transmitted via MQTT telemetry over TLS to an edge gateway and centralized cloud broker. A Python machine learning microservice continuously evaluates streaming telemetry alongside 7-day precipitation forecasts from OpenWeatherMap, historical drainage curves, and crop-specific evapotranspiration rates to dynamically predict optimal irrigation schedules and water volume requirements per zone. The cloud backend, built with Node.js, Express, and PostgreSQL with TimescaleDB for time-series telemetry, controls multi-channel solenoid valve relays with automated fail-safe watchdog timers to prevent flooding if network connectivity drops. Farmers and agronomists interact through a responsive web and mobile dashboard featuring live field heatmaps, per-zone manual valve overrides, leak detection alerts, and historical water savings analytics. Deliverables include micro-controller firmware with power-saving deep sleep cycles, secure MQTT broker pipelines, REST APIs with JWT authentication, predictive ML models, and comprehensive hardware-in-the-loop validation suites.",
    features: [
      "Soil moisture and temperature monitoring via ESP32",
      "MQTT-based sensor data streaming",
      "ML model for optimal irrigation prediction",
      "Weather forecast integration",
      "Per-zone irrigation scheduling",
      "Manual override controls",
      "Water-savings analytics dashboard",
      "Mobile-friendly monitoring interface",
    ],
    requirements: [
      "ESP32 microcontroller with soil moisture sensors",
      "MQTT broker for real-time telemetry",
      "Cloud backend with ML pipeline",
      "React or React Native frontend",
      "Weather API integration",
      "Water pump control interface",
    ],
    deliverables: [
      "Hardware prototype with sensor array",
      "Cloud backend with REST API",
      "ML model for irrigation scheduling",
      "Mobile analytics dashboard",
      "System integration documentation",
    ],
    suggestedSkills: ["Python", "React", "Node.js", "TensorFlow"],
    clientRequirements: "ESP32 soil-moisture sensors, real-time MQTT telemetry, ML-based prediction, mobile dashboard with water usage analytics, per-zone scheduling.",
  },
  {
    id: "project-management",
    title: "Project Management System",
    domain: "Web Application",
    methodology: "SCRUM",
    domainIcon: "briefcase-outline",
    tags: ["Web", "Collaboration", "Scheduling"],
    objective: "Develop a full-featured project management platform for team collaboration and task tracking.",
    description: "The Enterprise Project Management and Algorithmic Resource Allocation System is an end-to-end collaborative platform engineered for high-velocity software engineering, cross-functional product squads, and academic project teams. The platform tackles coordination bottlenecks, opaque progress tracking, and unbalanced developer workloads by unifying backlog decomposition, agile sprint planning, and algorithmic skill matching into a single cohesive workspace. Teams manage work across customizable Kanban boards with strict Work-In-Progress (WIP) column limits, Definition of Ready and Definition of Done verification checklists, and automated swimlane filters. Sprint planning features interactive backlog grooming, story point estimation with planning poker, burndown velocity charts, and cumulative flow diagrams. At the core of the platform is an advanced algorithmic scheduling engine that leverages Greedy priority heuristics, Topological Sort for acyclic task dependency graph resolution, and Branch & Bound combinatorial optimization to automatically assign backlog tasks to team members based on their verified competency profiles, past velocity, and real-time availability. Real-time collaboration is powered by Socket.IO WebSockets, delivering live board synchronization, teammate presence indicators, instant status change broadcasts, and threaded task comments. The robust backend architecture is built with Node.js, Express, and MongoDB Atlas, protected by JWT authentication, granular role-based access control (RBAC), and automated audit logs. Key deliverables include responsive web interfaces, RESTful microservices, exportable PDF/CSV retrospectives, and integration webhooks.",
    features: [
      "Kanban and list views for tasks",
      "Sprint planning and velocity tracking",
      "Real-time team collaboration",
      "Gantt chart timeline visualization",
      "Resource allocation and workload balancing",
      "File attachments and document sharing",
      "Automated notifications and reminders",
      "Role-based access control",
    ],
    requirements: [
      "Node.js/Express backend with MongoDB",
      "React frontend with drag-and-drop",
      "WebSocket for real-time updates",
      "JWT authentication system",
      "Email notification service",
      "File storage integration",
    ],
    deliverables: [
      "Responsive web application",
      "REST API with full documentation",
      "Real-time notification system",
      "Admin dashboard with analytics",
      "User guide and deployment docs",
    ],
    suggestedSkills: ["React", "Node.js", "MongoDB", "TypeScript"],
    clientRequirements: "Task management with Kanban/list views, sprint planning, real-time collaboration, Gantt charts, role-based access, notification system.",
  },
  {
    id: "phishshield",
    title: "PhishShield — Phishing Detection",
    domain: "Cybersecurity",
    methodology: "WATERFALL",
    domainIcon: "shield-outline",
    tags: ["Cybersecurity", "ML", "DBMS", "Email Security"],
    objective: "Create an intelligent phishing detection system that analyzes emails and URLs for threats.",
    description: "PhishShield is an enterprise-grade automated phishing and credential harvesting defense ecosystem designed to safeguard corporate communication channels, educational email domains, and end users against sophisticated social engineering threats. As email-borne attacks become increasingly evasive, PhishShield implements a multi-layered detection and quarantine pipeline that inspects inbound email messages, embedded hyperlinks, and suspicious domain registrations in real time. The ingestion engine parses RFC 822 email structures, validating cryptographic authentication protocols including SPF, DKIM, and DMARC alignment, while inspecting routing headers for anomalous mail transfer agents. The threat analysis core extracts multi-modal feature vectors: lexical URL properties, typosquatting Hamming distances, WHOIS domain age, and SSL certificate legitimacy, combined with an NLP classification pipeline using fine-tuned DistilBERT and XGBoost ensembles to analyze email text and attachments for coercive urgency and deceptive intent. A lightweight browser extension for Chrome and Firefox scans navigated web destinations, providing zero-latency visual warnings and blocking access to known malicious domains. The security operations center (SOC) web dashboard provides security analysts with threat intelligence feeds, attack origin geographic heatmaps, automated detonation sandbox reports, and single-click threat containment. Built with Python FastAPI, Node.js, and PostgreSQL for structured threat indicators, PhishShield delivers comprehensive API documentation, SIEM log forwarding in CEF format, and stringent static and dynamic security test compliance.",
    features: [
      "Email header and body analysis",
      "URL reputation scoring with ML classifier",
      "Real-time phishing threat dashboard",
      "Browser extension for URL scanning",
      "Threat intelligence database",
      "Automated alert system for detected threats",
      "Historical threat analysis and reporting",
      "Admin panel with threat management",
    ],
    requirements: [
      "Python backend with Flask/FastAPI",
      "ML classification model for phishing detection",
      "PostgreSQL database for threat records",
      "React frontend dashboard",
      "Browser extension (Chrome/Firefox)",
      "Email parsing library",
    ],
    deliverables: [
      "ML phishing detection model",
      "REST API for threat analysis",
      "Web dashboard with real-time alerts",
      "Browser extension for URL scanning",
      "Threat database and reporting module",
    ],
    suggestedSkills: ["Python", "React", "PostgreSQL", "TensorFlow"],
    clientRequirements: "Email phishing detection with ML classifier, URL reputation scoring, browser extension, real-time threat dashboard, historical reporting.",
  },
  {
    id: "kavach",
    title: "Kavach — Smart Structural Safety System",
    domain: "IoT",
    methodology: "WATERFALL",
    domainIcon: "shield-checkmark-outline",
    tags: ["IoT", "Structural Monitoring", "Safety", "ML"],
    objective: "Build a structural health monitoring system using IoT vibration sensors for building safety.",
    description: "Kavach is an autonomous structural health monitoring and seismic safety platform designed to provide continuous real-time stability assessments and early warnings for civil infrastructure, including bridges, tunnels, high-rise commercial buildings, and industrial facilities. The platform mitigates the hazards of catastrophic structural failures by detecting micro-vibrations, material fatigue, and structural tilt shifts long before visible surface cracks emerge. The edge sensor infrastructure deploys multi-axis industrial MEMS accelerometers (ADXL355), piezoelectric strain transducers, and laser inclinometers connected to hardened microcontrollers. Edge nodes run digital signal processing algorithms including Fast Fourier Transforms (FFT) and Butterworth band-pass filtering to calculate structural resonant frequencies and spectral density while rejecting transient ambient environmental noise from traffic or wind. Telemetry is streamed over MQTT with mutual TLS (mTLS) to an event ingestion cluster, persisting high-frequency sensor readings in TimescaleDB. The cloud machine learning engine utilizes Isolation Forests and LSTM autoencoders to discover vibration anomalies and calculate real-time structural health indices. A 3D digital twin dashboard renders building stress contours, floor deflection heatmaps, and long-term degradation trajectories. When seismic thresholds are exceeded, the fail-safe emergency sub-system dispatches instant multi-channel alerts via sirens, SMS broadcasts, and building management protocols to ground elevators and shut off gas mains. Deliverables include calibrated sensor schematics, processing microservices, and compliance audit reports.",
    features: [
      "Vibration and tilt sensor monitoring",
      "Real-time structural health scoring",
      "ML-based anomaly detection",
      "Emergency alert system with SMS/push notifications",
      "Historical vibration data visualization",
      "Building digital twin representation",
      "Compliance reporting for safety standards",
      "Multi-building monitoring dashboard",
    ],
    requirements: [
      "Accelerometer and tilt sensors with Arduino/ESP32",
      "Cloud backend for sensor data processing",
      "ML model for structural anomaly detection",
      "React dashboard for monitoring",
      "SMS/push notification service",
      "Time-series database for sensor data",
    ],
    deliverables: [
      "Sensor hardware prototype",
      "Cloud data processing pipeline",
      "ML anomaly detection model",
      "Real-time monitoring dashboard",
      "Alert and notification system",
    ],
    suggestedSkills: ["Python", "React", "Node.js", "TensorFlow"],
    clientRequirements: "IoT vibration sensors, real-time structural health scoring, ML anomaly detection, emergency alerts, multi-building dashboard, compliance reporting.",
  },
  {
    id: "ecommerce",
    title: "E-Commerce Platform",
    domain: "Web Application",
    methodology: "SCRUM",
    domainIcon: "cart-outline",
    tags: ["Web", "E-Commerce", "Payments"],
    objective: "Develop a scalable e-commerce platform with product management, cart, and payment processing.",
    description: "The Next-Generation Omnichannel E-Commerce and Inventory Management Platform is a high-availability retail marketplace solution engineered to support high-concurrency shopping, dynamic catalog discovery, and frictionless order fulfillment. Addressing the limitations of legacy monolithic storefronts, the platform provides a modular architecture with high-speed product browsing, personalized merchandising, and resilient checkout pipelines. The catalog subsystem features Elasticsearch indexing for instant typo-tolerant product searches, faceted multi-criteria filtering, inventory variant tracking, and real-time stock alerts. Customers benefit from a responsive shopping cart with automatic price calculation, coupon validation, dynamic shipping fee estimation, and flexible guest or authenticated checkout. The checkout flow orchestrates payments through Stripe, PayPal, and Razorpay, adhering to strict PCI-DSS standards with tokenized card handling, 3D Secure 2.0 authentication, and idempotent webhook reconciliation. A predictive recommendation microservice uses collaborative filtering and customer session telemetry to offer relevant cross-sell bundles and personalized product feeds. The merchant administration portal empowers store owners with inventory replenishment alerts, automated supplier purchase orders, parcel tracking integrations with major logistics carriers, and real-time sales performance metrics. Built with Node.js, Express, React, and MongoDB Atlas with Redis distributed caching for hot session data, the platform includes comprehensive end-to-end Cypress test coverage, Docker container deployment manifests, and automated CI/CD pipelines.",
    features: [
      "Product catalog with search and filters",
      "Shopping cart and checkout flow",
      "Secure payment gateway integration",
      "Order tracking and history",
      "Product recommendation engine",
      "Admin dashboard with sales analytics",
      "Inventory management system",
      "Email notifications for orders",
    ],
    requirements: [
      "Node.js/Express backend with MongoDB",
      "React frontend with responsive design",
      "Payment gateway (Stripe/Razorpay)",
      "JWT authentication",
      "Image upload and CDN",
      "Email service for notifications",
    ],
    deliverables: [
      "Responsive e-commerce web application",
      "Payment processing integration",
      "Admin analytics dashboard",
      "Inventory management module",
      "API documentation",
    ],
    suggestedSkills: ["React", "Node.js", "MongoDB", "TypeScript"],
    clientRequirements: "Product catalog, cart checkout, secure payments, order tracking, recommendation engine, admin dashboard with sales analytics and inventory.",
  },
  {
    id: "hospital-mgmt",
    title: "Hospital Management System",
    domain: "Web Application",
    methodology: "WATERFALL",
    domainIcon: "medkit-outline",
    tags: ["Healthcare", "DBMS", "Records", "Billing"],
    objective: "Create a comprehensive hospital management system for patient records, scheduling, and billing.",
    description: "The Integrated Hospital Information Management and Clinical Workflow System is an enterprise electronic health records (EHR) and healthcare operations platform designed for hospitals, outpatient clinics, and multi-specialty healthcare networks. The system streamlines patient care pathways, eliminates administrative redundancies, and safeguards patient data privacy in accordance with stringent regulatory standards including HIPAA and HL7 FHIR. The clinical module provides centralized electronic medical records including demographic profiles, longitudinal patient histories, allergy alerts, vital signs charts, ICD-10 diagnostic coding, and digital physician consultation notes. The outpatient and inpatient scheduling engine manages multi-doctor appointment slots, operating room schedules, automated SMS reminder notifications, and digital patient queue displays in waiting departments. The integrated pharmacy and laboratory modules handle digital prescription dispensing, computerized physician order entries (CPOE), barcode-tracked specimen workflows, automated diagnostic analyzer data ingestion, and secure digital lab report generation. A comprehensive medical billing engine coordinates insurance pre-authorization, patient co-payments, itemized invoice creation, and automated claim submission tracking. Granular role-based access control enforces strict confidentiality boundaries across medical doctors, triage nurses, lab technicians, pharmacists, and billing administrators, backed by immutable database audit logs and AES-256 data encryption at rest and in transit. Deliverables include web portals, REST APIs, and clinical training manuals.",
    features: [
      "Electronic health records (EHR)",
      "Appointment scheduling and queue management",
      "Prescription and medication management",
      "Lab results integration and viewing",
      "Billing and invoice generation",
      "Department-wise dashboards",
      "Real-time bed occupancy tracking",
      "Audit logging for compliance",
    ],
    requirements: [
      "Node.js backend with PostgreSQL",
      "React frontend with role-based views",
      "Secure authentication with RBAC",
      "PDF generation for prescriptions/invoices",
      "Real-time notification system",
      "Data encryption for patient privacy",
    ],
    deliverables: [
      "Patient management web application",
      "Doctor and nurse portal",
      "Admin analytics dashboard",
      "Billing and reporting module",
      "Security and compliance documentation",
    ],
    suggestedSkills: ["React", "Node.js", "PostgreSQL", "TypeScript"],
    clientRequirements: "EHR system, appointment scheduling, billing, lab integration, role-based access for doctors/nurses/admin, audit logging, HIPAA compliance.",
  },
  {
    id: "ai-learning",
    title: "AI Learning Platform",
    domain: "AI",
    methodology: "SCRUM",
    domainIcon: "school-outline",
    tags: ["AI", "Education", "Adaptive Learning"],
    objective: "Build an adaptive learning platform using AI to personalize educational content for students.",
    description: "The Adaptive AI-Powered Learning and Dynamic Skill Verification Platform is an intelligent educational ecosystem created to deliver personalized curriculum pathways, interactive assessments, and deep pedagogical insights for learners and educators. Addressing the one-size-fits-all shortcomings of conventional learning management systems, the platform utilizes cognitive artificial intelligence to adapt content difficulty to each student's unique learning curve. The adaptive sequencing engine utilizes Bayesian Knowledge Tracing (BKT) and Item Response Theory (IRT) to evaluate concept mastery in real time, serving targeted remedial explanations or challenging advanced problem sets. The automated quiz and assessment generator uses large language models with specialized instructional prompts to generate high-quality multiple-choice questions, interactive coding challenges, and conceptual prompts with detailed solution rationales. Students engage through an interactive multimedia player featuring video lesson streaming, synchronized code sandboxes, and timestamped personal study notes. A collaborative discussion hub integrates AI-assisted quality moderation, semantic question clustering, and peer answer upvoting. The educator analytics dashboard equips teachers with real-time cohort competency distributions, student struggle indicators, and automated grading summaries. Built on Python FastAPI, Node.js, React, MongoDB Atlas, and ChromaDB for semantic vector retrieval of course materials, the platform ensures low-latency WebSocket interactions and complies with modern accessibility standards (WCAG 2.1). Deliverables include web apps, APIs, and student evaluation suites.",
    features: [
      "AI-driven content recommendation",
      "Adaptive quiz generation based on skill level",
      "Progress tracking with learning analytics",
      "Interactive video lessons with bookmarking",
      "Peer discussion forums",
      "Teacher dashboard with student insights",
      "Gamification with badges and streaks",
      "Multi-language content support",
    ],
    requirements: [
      "Python/FastAPI backend with ML pipeline",
      "React frontend with video player",
      "NLP model for content recommendation",
      "MongoDB for user profiles and content",
      "WebSocket for real-time collaboration",
      "Cloud storage for video content",
    ],
    deliverables: [
      "Adaptive learning web application",
      "AI recommendation engine",
      "Teacher analytics dashboard",
      "Quiz generation system",
      "API documentation and deployment guide",
    ],
    suggestedSkills: ["Python", "React", "MongoDB", "TensorFlow"],
    clientRequirements: "Adaptive learning with AI recommendations, quiz generation, progress tracking, teacher dashboard, gamification, multi-language support.",
  },
];
